[package]
name = "dioxus-kit"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
description = "General-purpose, app-agnostic utilities for Dioxus web apps (currently a framework-level toast queue)."

[lib]
path = "src/lib.rs"

[dependencies]
dioxus = { workspace = true }
browser-kit = { git = "https://github.com/clemenscodes/browser-kit", tag = "v0.2.0" }
ddd = { git = "https://github.com/clemenscodes/ddd", rev = "3192a69" }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", default-features = false }
